#Include, functions
#Include, loopWithSameKey.ahk
#Include, googleSearch.ahk
#Include, cmdOpenerInSelection.ahk
#Include, CheckScriptUpdate.ahk
#Include, brave.ahk
#Include, MButton.ahk
#Include, directoryOpener.ahk
#Include, %A_ScriptDir%